-- MySQL Script generated by MySQL Workbench
-- Sun 26 Apr 2020 16:11:47 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ocpizza
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ocpizza
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ocpizza` ;
USE `ocpizza` ;

-- -----------------------------------------------------
-- Table `ocpizza`.`pizzeria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ocpizza`.`pizzeria` ;

CREATE TABLE IF NOT EXISTS `ocpizza`.`pizzeria` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `lat` DECIMAL(9,6) NULL,
  `long` DECIMAL(9,6) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ocpizza`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ocpizza`.`user` ;

CREATE TABLE IF NOT EXISTS `ocpizza`.`user` (
  `id` INT NOT NULL,
  `username` VARCHAR(16) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(255) NULL,
  `phone_number` VARCHAR(14) NOT NULL,
  `password` VARCHAR(32) NOT NULL,
  `role` VARCHAR(15) NULL,
  `pizzeria` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_1_idx` (`pizzeria` ASC) VISIBLE,
  CONSTRAINT `fk_user_1`
    FOREIGN KEY (`pizzeria`)
    REFERENCES `ocpizza`.`pizzeria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ocpizza`.`order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ocpizza`.`order` ;

CREATE TABLE IF NOT EXISTS `ocpizza`.`order` (
  `id` INT NOT NULL,
  `state` VARCHAR(10) NULL,
  `user_id` INT NULL,
  `employee_in_charge` INT NULL,
  `pizzeria_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_order_1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_order_2_idx` (`employee_in_charge` ASC) VISIBLE,
  INDEX `fk_order_3_idx` (`pizzeria_id` ASC) VISIBLE,
  CONSTRAINT `fk_order_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `ocpizza`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_2`
    FOREIGN KEY (`employee_in_charge`)
    REFERENCES `ocpizza`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_3`
    FOREIGN KEY (`pizzeria_id`)
    REFERENCES `ocpizza`.`pizzeria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ocpizza`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ocpizza`.`category` ;

CREATE TABLE IF NOT EXISTS `ocpizza`.`category` (
  `id` INT NOT NULL,
  `category_name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ocpizza`.`product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ocpizza`.`product` ;

CREATE TABLE IF NOT EXISTS `ocpizza`.`product` (
  `id` INT NOT NULL,
  `category_id` INT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` MEDIUMTEXT NOT NULL,
  `price` DECIMAL(5,2) NOT NULL,
  `is_menu` TINYINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_product_1_idx` (`category_id` ASC) VISIBLE,
  CONSTRAINT `fk_product_1`
    FOREIGN KEY (`category_id`)
    REFERENCES `ocpizza`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ocpizza`.`picture`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ocpizza`.`picture` ;

CREATE TABLE IF NOT EXISTS `ocpizza`.`picture` (
  `id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `url` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `url_UNIQUE` (`url` ASC) VISIBLE,
  INDEX `fk_picture_1_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_picture_1`
    FOREIGN KEY (`product_id`)
    REFERENCES `ocpizza`.`product` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ocpizza`.`association_menu_product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ocpizza`.`association_menu_product` ;

CREATE TABLE IF NOT EXISTS `ocpizza`.`association_menu_product` (
  `menu_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  PRIMARY KEY (`menu_id`, `product_id`),
  INDEX `fk_association_menu_product_2_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_association_menu_product_1`
    FOREIGN KEY (`menu_id`)
    REFERENCES `ocpizza`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_association_menu_product_2`
    FOREIGN KEY (`product_id`)
    REFERENCES `ocpizza`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ocpizza`.`ingredient`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ocpizza`.`ingredient` ;

CREATE TABLE IF NOT EXISTS `ocpizza`.`ingredient` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `unit` VARCHAR(10) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ocpizza`.`association_product_ingredient`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ocpizza`.`association_product_ingredient` ;

CREATE TABLE IF NOT EXISTS `ocpizza`.`association_product_ingredient` (
  `product_id` INT NOT NULL,
  `ingredient_id` INT NOT NULL,
  `quantity` INT NOT NULL DEFAULT 1,
  PRIMARY KEY (`product_id`, `ingredient_id`),
  INDEX `fk_association_product_ingredient_2_idx` (`ingredient_id` ASC) VISIBLE,
  CONSTRAINT `fk_association_product_ingredient_1`
    FOREIGN KEY (`product_id`)
    REFERENCES `ocpizza`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_association_product_ingredient_2`
    FOREIGN KEY (`ingredient_id`)
    REFERENCES `ocpizza`.`ingredient` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ocpizza`.`association_order_product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ocpizza`.`association_order_product` ;

CREATE TABLE IF NOT EXISTS `ocpizza`.`association_order_product` (
  `order_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `quantity` INT NOT NULL DEFAULT 1,
  PRIMARY KEY (`order_id`, `product_id`),
  INDEX `fk_association_order_product_2_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_association_order_product_1`
    FOREIGN KEY (`order_id`)
    REFERENCES `ocpizza`.`order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_association_order_product_2`
    FOREIGN KEY (`product_id`)
    REFERENCES `ocpizza`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ocpizza`.`stock`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ocpizza`.`stock` ;

CREATE TABLE IF NOT EXISTS `ocpizza`.`stock` (
  `pizzeria_id` INT NOT NULL,
  `ingredient_id` INT NOT NULL,
  `quantity` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`pizzeria_id`, `ingredient_id`),
  INDEX `fk_association_pizzeria_ingredient_2_idx` (`ingredient_id` ASC) VISIBLE,
  CONSTRAINT `fk_association_pizzeria_ingredient_1`
    FOREIGN KEY (`pizzeria_id`)
    REFERENCES `ocpizza`.`pizzeria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_association_pizzeria_ingredient_2`
    FOREIGN KEY (`ingredient_id`)
    REFERENCES `ocpizza`.`ingredient` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ocpizza`.`promotion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ocpizza`.`promotion` ;

CREATE TABLE IF NOT EXISTS `ocpizza`.`promotion` (
  `id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `percentage` DECIMAL(5,2) NOT NULL,
  `start_of_promotion` DATE NULL,
  `end_of_promotion` DATE NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_promotion_1_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_promotion_1`
    FOREIGN KEY (`product_id`)
    REFERENCES `ocpizza`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ocpizza`.`address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ocpizza`.`address` ;

CREATE TABLE IF NOT EXISTS `ocpizza`.`address` (
  `id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `street_address` VARCHAR(80) NOT NULL,
  `complement` VARCHAR(80) NULL,
  `postal_code` VARCHAR(10) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_address_1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_address_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `ocpizza`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ocpizza`.`payment_method`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ocpizza`.`payment_method` ;

CREATE TABLE IF NOT EXISTS `ocpizza`.`payment_method` (
  `id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `card_number` VARCHAR(13) NOT NULL,
  `name` VARCHAR(45) NULL,
  `expiration_date` DATE NOT NULL,
  `cryptogram` VARCHAR(4) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_payment_method_1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_payment_method_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `ocpizza`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ocpizza`.`stockrecord`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ocpizza`.`stockrecord` ;

CREATE TABLE IF NOT EXISTS `ocpizza`.`stockrecord` (
  `id` INT NOT NULL,
  `pizzeria_id` INT NOT NULL,
  `ingredient_id` INT NOT NULL,
  `quantity` INT NOT NULL,
  `is_addition` TINYINT NOT NULL,
  `date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_stockrecord_1_idx` (`pizzeria_id` ASC, `ingredient_id` ASC) VISIBLE,
  CONSTRAINT `fk_stockrecord_1`
    FOREIGN KEY (`pizzeria_id` , `ingredient_id`)
    REFERENCES `ocpizza`.`stock` (`pizzeria_id` , `ingredient_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
